### ISSUE TITLE
sapp4ua returns 403 forbidden error

### ISSUE THREAD

**Issue by astrochun** [astrochun/uarizona-salary-app#82]
This maybe be related to account security changes:

```
2022-05-04T22:34:06.721461+00:00 app[web.1]: Loading data from Google Drive
2022-05-04T22:34:06.806435+00:00 heroku[router]: at=info method=GET path="/static/js/29.7729fb97.chunk.js" host=sapp4ua.herokuapp.com request_id=b3c49af1-cc6c-4781-a67b-4c4b327e284f fwd="24.251.126.84" dyno=web.1 connect=0ms service=4ms status=200 bytes=896 protocol=https
2022-05-04T22:34:06.846649+00:00 heroku[router]: at=info method=GET path="/static/media/SourceSansPro-Bold.12e6acd2.ttf" host=sapp4ua.herokuapp.com request_id=a4a68fb2-6e36-41c8-9ad9-158e3e0fc4b0 fwd="24.251.126.84" dyno=web.1 connect=0ms service=12ms status=200 bytes=267790 protocol=https
2022-05-04T22:34:06.971967+00:00 heroku[router]: at=info method=GET path="/static/media/SourceCodePro-Regular.70cc7ff2.ttf" host=sapp4ua.herokuapp.com request_id=0f51c3db-03d1-477e-99ca-2330b458a0aa fwd="24.251.126.84" dyno=web.1 connect=2ms service=16ms status=200 bytes=193142 protocol=https
2022-05-04T22:34:11.836753+00:00 app[web.1]: 2022-05-04 22:34:11.836 Traceback (most recent call last):
2022-05-04T22:34:11.836761+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/streamlit/legacy_caching/caching.py", line 509, in get_or_create_cached_value
2022-05-04T22:34:11.836762+00:00 app[web.1]: return_value = _read_from_cache(
2022-05-04T22:34:11.836764+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/streamlit/legacy_caching/caching.py", line 308, in _read_from_cache
2022-05-04T22:34:11.836764+00:00 app[web.1]: raise e
2022-05-04T22:34:11.836765+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/streamlit/legacy_caching/caching.py", line 293, in _read_from_cache
2022-05-04T22:34:11.836765+00:00 app[web.1]: return _read_from_mem_cache(
2022-05-04T22:34:11.836765+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/streamlit/legacy_caching/caching.py", line 212, in _read_from_mem_cache
2022-05-04T22:34:11.836766+00:00 app[web.1]: raise CacheKeyNotFoundError("Key not found in mem cache")
2022-05-04T22:34:11.836767+00:00 app[web.1]: streamlit.legacy_caching.caching.CacheKeyNotFoundError: Key not found in mem cache
2022-05-04T22:34:11.836767+00:00 app[web.1]: 
2022-05-04T22:34:11.836768+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2022-05-04T22:34:11.836768+00:00 app[web.1]: 
2022-05-04T22:34:11.836768+00:00 app[web.1]: Traceback (most recent call last):
2022-05-04T22:34:11.836774+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/streamlit/script_runner.py", line 354, in _run_script
2022-05-04T22:34:11.836775+00:00 app[web.1]: exec(code, module.__dict__)
2022-05-04T22:34:11.836775+00:00 app[web.1]: File "/app/salary_app/main.py", line 170, in <module>
2022-05-04T22:34:11.836776+00:00 app[web.1]: main(bokeh=True, local=args.local)
2022-05-04T22:34:11.836776+00:00 app[web.1]: File "/app/salary_app/main.py", line 102, in main
2022-05-04T22:34:11.836776+00:00 app[web.1]: data_dict, unique_df = load_data(local=local)
2022-05-04T22:34:11.836777+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/streamlit/legacy_caching/caching.py", line 543, in wrapped_func
2022-05-04T22:34:11.836777+00:00 app[web.1]: return get_or_create_cached_value()
2022-05-04T22:34:11.836777+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/streamlit/legacy_caching/caching.py", line 527, in get_or_create_cached_value
2022-05-04T22:34:11.836778+00:00 app[web.1]: return_value = func(*args, **kwargs)
2022-05-04T22:34:11.836778+00:00 app[web.1]: File "/app/salary_app/main.py", line 39, in load_data
2022-05-04T22:34:11.836778+00:00 app[web.1]: data_dict[year_split] = pd.read_csv(url)
2022-05-04T22:34:11.836779+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
2022-05-04T22:34:11.836779+00:00 app[web.1]: return func(*args, **kwargs)
2022-05-04T22:34:11.836779+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
2022-05-04T22:34:11.836780+00:00 app[web.1]: return _read(filepath_or_buffer, kwds)
2022-05-04T22:34:11.836780+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
2022-05-04T22:34:11.836780+00:00 app[web.1]: parser = TextFileReader(filepath_or_buffer, **kwds)
2022-05-04T22:34:11.836781+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
2022-05-04T22:34:11.836781+00:00 app[web.1]: self._engine = self._make_engine(self.engine)
2022-05-04T22:34:11.836781+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
2022-05-04T22:34:11.836782+00:00 app[web.1]: return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
2022-05-04T22:34:11.836782+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
2022-05-04T22:34:11.836782+00:00 app[web.1]: self._open_handles(src, kwds)
2022-05-04T22:34:11.836783+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
2022-05-04T22:34:11.836783+00:00 app[web.1]: self.handles = get_handle(
2022-05-04T22:34:11.836783+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pandas/io/common.py", line 609, in get_handle
2022-05-04T22:34:11.836783+00:00 app[web.1]: ioargs = _get_filepath_or_buffer(
2022-05-04T22:34:11.836784+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pandas/io/common.py", line 312, in _get_filepath_or_buffer
2022-05-04T22:34:11.836784+00:00 app[web.1]: with urlopen(req_info) as req:
2022-05-04T22:34:11.836784+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pandas/io/common.py", line 212, in urlopen
2022-05-04T22:34:11.836784+00:00 app[web.1]: return urllib.request.urlopen(*args, **kwargs)
2022-05-04T22:34:11.836785+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 214, in urlopen
2022-05-04T22:34:11.836785+00:00 app[web.1]: return opener.open(url, data, timeout)
2022-05-04T22:34:11.836785+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/hooks/external_urllib.py", line 41, in _nr_wrapper
2022-05-04T22:34:11.836785+00:00 app[web.1]: return wrapped(*args, **kwargs)
2022-05-04T22:34:11.836786+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 523, in open
2022-05-04T22:34:11.836786+00:00 app[web.1]: response = meth(req, response)
2022-05-04T22:34:11.836786+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 632, in http_response
2022-05-04T22:34:11.836786+00:00 app[web.1]: response = self.parent.error(
2022-05-04T22:34:11.836787+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 555, in error
2022-05-04T22:34:11.836787+00:00 app[web.1]: result = self._call_chain(*args)
2022-05-04T22:34:11.836787+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 494, in _call_chain
2022-05-04T22:34:11.836788+00:00 app[web.1]: result = func(*args)
2022-05-04T22:34:11.836788+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 747, in http_error_302
2022-05-04T22:34:11.836793+00:00 app[web.1]: return self.parent.open(new, timeout=req.timeout)
2022-05-04T22:34:11.836794+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/hooks/external_urllib.py", line 41, in _nr_wrapper
2022-05-04T22:34:11.836794+00:00 app[web.1]: return wrapped(*args, **kwargs)
2022-05-04T22:34:11.836795+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 523, in open
2022-05-04T22:34:11.836795+00:00 app[web.1]: response = meth(req, response)
2022-05-04T22:34:11.836795+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 632, in http_response
2022-05-04T22:34:11.836795+00:00 app[web.1]: response = self.parent.error(
2022-05-04T22:34:11.836796+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 561, in error
2022-05-04T22:34:11.836796+00:00 app[web.1]: return self._call_chain(*args)
2022-05-04T22:34:11.836796+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 494, in _call_chain
2022-05-04T22:34:11.836797+00:00 app[web.1]: result = func(*args)
2022-05-04T22:34:11.836797+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 641, in http_error_default
2022-05-04T22:34:11.836798+00:00 app[web.1]: raise HTTPError(req.full_url, code, msg, hdrs, fp)
2022-05-04T22:34:11.836798+00:00 app[web.1]: urllib.error.HTTPError: HTTP Error 403: Forbidden
2022-05-04T22:34:11.836798+00:00 app[web.1]: 
2022-05-04T22:34:12.303611+00:00 heroku[router]: at=info method=GET path="/static/media/SourceSansPro-SemiBold.43cc81b4.ttf" host=sapp4ua.herokuapp.com request_id=e05af669-cc1b-4e18-9e39-66a01669043b fwd="24.251.126.84" dyno=web.1 connect=0ms service=356ms status=200 bytes=268682 protocol=https
2022-05-04T22:36:08.675948+00:00 heroku[router]: at=info method=HEAD path="/" host=sapp4ua.herokuapp.com request_id=ecdb19a0-b4da-4586-86ae-5e6dfb086e37 fwd="54.203.193.46" dyno=web.1 connect=0ms service=3ms status=200 bytes=403 protocol=https
```

**Comment by astrochun** [comment]
The issue is related to the Google Drive API. It seems that there are some quota limits that we continue to hit. In some cases, it works fine and in other cases, it returns this 403 error. The best solution is to host the data elsewhere (e.g. Dropbox). Dropbox was tested to be reliable on a GitPod and locally.
